name: Group CICD

on: [push]

jobs:
  print-group-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Group Name
        run: echo "This is our group work"
