name: Group CICD

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m $VENV venv
          source $VENV/bin/activate
          pip install -r requirements.txt || echo "No requirements.txt found or installation failed"

          

      - name: Run tests
        run: |
          source $VENV/bin/activate
          pytest 
